# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Plot SDG Indicator matching UNHCR RBM one for a country
#' @description This displays a chart to have a base of comparison when analyzing
#'               the results of UNHCR of UNHCR Result monitoring survey  
#'               The function includes a mapping table between RBM/RMS and SDG and 
#'               extract the data from https://unstats.un.org/SDGAPI/swagger/ 
#' @param country iso3 code for the country (easier to recall than the M49 used in the API)
#' @param rbm  the RBM variable name - that can match SDG 
#' @param years  years to filter the chart - for instance c(2000,2022)
#' 
#' @importFrom jsonlite fromJSON
#' @importFrom unhcrdatapackage reference
#' @importFrom janitor clean_names
#' 
#' @return a ggplot2 object
#' @noRd
#' @examples
#' plot_rbm_sdg( country = "ECU", 
#'           rbm = "impact2_2",
#'           years = c(2000, 2022)) 
plot_rbm_sdg <- function( country = "ECU", 
                      rbm = "outcome16_2",
                      years = c(2000, 2022))   {
  require(ggplot2)
  require(dplyr)
sdg_rbm <-  structure(list(
  indicator = c("1.4.1", "3.8.1", "16.9.1", "7.1.2", 
                             "7.1.1", "3.1.2", "6.1.1", "6.2.1", 
                             "8.10.2", "8.5.2", "1.4.2", "1.3.1", "16.1.4"), 
               
  SDG_indic = c("1.4.1 Proportion of population living in households with access to basic services", 
  "3.8.1 Coverage of essential health services (defined as the average coverage of essential services based on tracer interventions that include reproductive, maternal, newborn and child health, infectious diseases, non-communicable diseases and service capacity and access, among the general and the most disadvantaged population)", 
  "16.9.1 Proportion of children under 5 years of age whose births have been registered with a civil authority, by age", 
  "7.1.2 Proportion of population with primary reliance on clean fuels and technology", 
  "7.1.1 Proportion of population with access to electricity", 
  "3.1.2 Proportion of births attended by skilled health personnel", 
  "6.1.1 Proportion of population using safely managed drinking water services", 
  "6.2.1 Proportion of population using (a) safely managed sanitation services and (b) a hand-washing facility with soap and water", 
  "8.10.2 Proportion of adults (15 years and older) with an account at a bank or other financial institution or with a mobile-money-service provider", 
  "8.5.2 Unemployment rate, by sex, age and persons with disabilities", 
  "1.4.2 Proportion of total adult population with secure tenure rights to land, (a) with legally recognized documentation, and (b) who perceive their rights to land as secure, by sex and type of tenure", 
  "1.3.1 Proportion of population covered by social protection floors/systems, by sex, distinguishing children, unemployed persons, older persons, persons with disabilities, pregnant women, newborns, work-injury victims and the poor and the vulnerable", 
  "16.1.4 Proportion of population that feel safe walking alone around the area they live"), 
  RMS = c("impact2_2", "impact2_3", "outcome1_2", "outcome8_2", 
          "outcome9_2", "outcome10_2", "outcome12_1", "outcome12_2", "outcome13_1", 
          "outcome13_3", "outcome16_1", "outcome16_2", "impact3_3"),
  target = c("1.4", 
  "3.8", "16.9", "7.1", "7.1", "3.1", "6.1", "6.2", "8.10", "8.5", 
  "1.4", "1.3", "16.1"),
  
  description = c("By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance", 
  "Achieve universal health coverage, including financial risk protection, access to quality essential health-care services and access to safe, effective, quality and affordable essential medicines and vaccines for all", 
  "By 2030, provide legal identity for all, including birth registration", 
  "By 2030, ensure universal access to affordable, reliable and modern energy services", 
  "By 2030, ensure universal access to affordable, reliable and modern energy services", 
  "By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births", 
  "By 2030, achieve universal and equitable access to safe and affordable drinking water for all", 
  "By 2030, achieve access to adequate and equitable sanitation and hygiene for all and end open defecation, paying special attention to the needs of women and girls and those in vulnerable situations", "Strengthen the capacity of domestic financial institutions to encourage and expand access to banking, insurance and financial services for all", 
  "By 2030, achieve full and productive employment and decent work for all women and men, including for young people and persons with disabilities, and equal pay for work of equal value", 
  "By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance", 
  "Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable", 
  "Significantly reduce all forms of violence and related death rates everywhere")), 
  class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
  -13L))
  
 ctry <- unhcrdatapackage::reference |>
           filter(iso_3 == country ) |> 
           select(iso_3, ctryname, M49_code) 
  sdg_code_label <- sdg_rbm |>
           filter(RMS == rbm  )
  
  sdg_code <- sdg_rbm |>
           filter(RMS == rbm  ) |>
           pull(indicator)
  
  
  
  #cat(paste0("\n \n -------\n Pulling RMS Host country comparison data for ", ctry$ctryname,  "\n\n"))
  #cat(paste0("Retrieving now : ", sdg_code_label$SDG_indic , "\n"))

  url<-paste0("https://unstats.un.org/SDGAPI/v1/sdg/Indicator/Data?indicator=",
              sdg_code,"&areaCode=", ctry$M49_code)
  datcall <- jsonlite::fromJSON(url)
  Ind1 <- as.data.frame(datcall$data)


  ## Check if the API did return something
  if(nrow(Ind1) == 0) {
        #cat(paste0("\n ಠ_ಠ  \n No data rcould be etrieved  from API for ", sdg_code_label$SDG_indic , " in country: ", ctry$ctryname ,"n\n"))
        p <-  ggplot() +     
             annotate("text",  x = 1, y = 1,  size = 10,
             label = stringr::str_wrap(paste0("\n ಠ_ಠ  \n No data could be retrieved from  UNStat API for: ", 
                          sdg_code_label$SDG_indic , " (related to UNHCR Indicator ", rbm ,
                          ") in country: ", 
                          ctry$ctryname ,"."), 50 ) ) +   theme_void()
    
    
       return(p)
    } else {
       # cat(paste0("Done! ", nrow(Ind1), " records gathered   ヽ(´▽`)/ \n\n"))
  
  ## Remove rows when value is NaN
  Ind1 <- Ind1[ !(is.nan(Ind1$value)), ]
  ## Replace NaN by NA for upper and lower Bound
  Ind1$upperBound <- ifelse(is.nan(Ind1$upperBound), NA , Ind1$upperBound )
  Ind1$lowerBound <- ifelse(is.nan(Ind1$lowerBound), NA , Ind1$lowerBound )

  #cat ("sleep 3 sec between each indicators...")
  #Sys.sleep(3)


  #Ind1$target <- as.character(Ind1$target )
 Ind1  <- Ind1 %>% 
           as.data.frame()  %>%
           janitor::clean_names() %>%  
           ## Cleaning a few country name for better legibility
            dplyr::mutate ( geo_area_name = stringr::str_replace(geo_area_name, "Venezuela \\(Bolivarian Republic of\\)", "Venezuela"),
                      geo_area_name = stringr::str_replace(geo_area_name,
                                                  "Bolivia \\(Plurinational State of\\)", 
                                                  "Bolivia")) #%>%  
           #dplyr::left_join(Goals, by="target")
   #names(Ind1)

   ## remove all empty disaggregation
   # Ind2 <- as.data.frame(Ind1[ , colSums(is.na(Ind1)) == 0])
   Ind2 <- Ind1%>%  
                   select(series_description, geo_area_name, time_period_start,value ) %>% 
                  group_by(series_description, geo_area_name, time_period_start) %>% 
      ## Aggregate base on Unit type - aka sum or average 
        summarize(valmean = mean(as.numeric(value)),
                  valsum = sum(as.numeric(value))  )%>% 
           #So we overprint in the right order
            arrange(time_period_start) #%>% 
      
    if( unique(Ind1$attributes$Units) %in% c("NUM_TH" , "NUMBER") ) {
        Ind2$value <- Ind2$valsum
      } else {
        Ind2$value <- Ind2$valmean
      }
    # names(Ind2)
   p <- ggplot(data =  Ind2, 
             aes(x = time_period_start,
                 y = value,
                 group = 1)) +
        geom_line( linewidth = 1.5, color = "#0072BC" ) +
        geom_point(shape =15, size = 2, color = "#0072BC") +  
        facet_wrap(~ series_description) +
       #scale_y_continuous(labels = unhcRstyle::format_si()) +
        scale_x_continuous(limits = years) +
        #geom_hline(yintercept = 0, size = 0.7, colour = "#333333") +
        unhcrthemes::theme_unhcr(font_size = 20) + ## Insert UNHCR Style
        theme(panel.grid.major.y  = element_line(color = "#cbcbcb"), 
              panel.grid.major.x  = element_blank(), 
              panel.grid.minor = element_blank(),
              #panel.grid.major.x = element_blank(),
              legend.position="none",
              strip.text.x = element_text(size = 8)) +
        labs(title = stringr::str_wrap(paste0( ctry$ctryname, ": ",sdg_code_label$description ), 80), 
             subtitle = stringr::str_wrap( paste0(sdg_code_label$SDG_indic, " (related to UNHCR Indicator ", rbm, ")"), 100),
             x = " ", 
             y = paste0(unique(Ind1$attributes$Units)),
             caption = stringr::str_wrap( paste0("Source: ", unique(Ind1$source), ", Data extracted from UNStat API"), 100))
   
        #  gghighlight::gghighlight(value >= mean(dfna1$value),
        # #value - sdval,
        #                  use_direct_label = FALSE) + 
        # geom_tile( data = yearfocus,
        #            aes(x = year, 
        #                y = value, 
        #                fill = as_factor((decade/10)%%2)),
        #            show.legend = FALSE) +
        # scale_fill_manual(values = c("0" = "white", 
        #                              "1" = "#99999922")) +  
   return(p)
   
  }
   
}
