# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

# usethis::use_rmarkdown_template(
#   template_name = "RMS_Report",
#   template_dir = NULL,
#   template_description = "RESULTS MONITORING SURVEY Data Collection REPORT",
#   template_create_dir = TRUE
# )
#' Generate an html / pdf country fact sheet 
#' 
#' This functions provides a quick access to a basic Statistical Fact sheet 
#' template that can be customized according to the needs
#' 
#' @param year Numeric value of the year (for instance 2022)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param folder folder within your project where to put the generated report. 
#' Folder will be created if it does not exist
#' 
#' @importFrom unhcrdown paged_simple
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#' 
#' @return nothing the file for the report is generated
#' 
#' @export 
#'

#' @examples
#' 
#' # template_rmsReport(year = 2022, country_asylum_iso3c = "USA",   folder = "Report")
#' 
#' 
template_rmsReport <- function(year = 2022,
                                   country_asylum_iso3c,
                                   folder = "Report")
  {
  
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(),"/",folder)
  if (!dir.exists(output_dir)) {dir.create(output_dir)}
  
  ctrname <- unhcrdatapackage::reference |>
             dplyr::filter( iso_3 == country_asylum_iso3c) |>
             dplyr::select(ctryname) |>
             dplyr::pull()
  
  rmarkdown::render(
    system.file("rmarkdown/templates/rms_report/skeleton/skeleton.Rmd", package = "rmsReport"),
    output_file = here::here(folder, paste0('RMS_Report-', country_asylum_iso3c, '-', year, '.html') ),
    params = list(countryname= ctrname,
                  country = country_asylum_iso3c, 
                  year = year)  )
 }
  
